---
# Modelo de Classificação de Análise de Sentimentos

---
### 01 - Definição do Problema de Negõcio

É a fundação do projeto. Nesta etapa, traduzimos uma necessidade da empresa em um objetivo claro para a Ciência de Dados. Definimos o que queremos resolver (automatizar, classificação de reviews de produtos, por exemplo), porque é importante (reduzir custos, agilizar a tomada de decisão) e como o sucesso será medido.

**Definição:**

Uma empresa de e-commerce deseja automatizar a análise de sentimentos de seus clientes. Atualmente, a análise é feita manualmente, o que é um processo lento. caro e que não escala com o volume de reviews recebidos diariamente.

**Objetivo:**

Criar um modelo Machine Learning que classifique automaticamente os reviews de produtos como **"positivo"** ou **"negativo"**.

**Benefícios Esperados:**

- **Eficiência:** Reduzir o tempo e o custo da análise de feedback;
- **Tomada de Decisão Rápida**: Permitir que as equipes de produtos e marketing identifiquem rapidamente produtos com problemas ou oportunidades de melhoria;
- **Priorização**: Direcionar reviews negativos para a equipe de suporte ao cliente de forma prioritária, melhorando a experiância do consumidor.

---
### 02 - Importação das Bibliotecas

In [23]:
# manipulacao de dados e visualizacao
import re
import pandas as pd
import numpy as np
import unicodedata
import seaborn as sns
import matplotlib.pyplot as plt

# pre-processamento e machine learning
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

In [24]:
# configuracao de visualizacao
sns.set_style('whitegrid')
%matplotlib inline

In [25]:
%reload_ext watermark
%watermark -a "Wolfdata"

Author: Wolfdata

In [26]:
%watermark --iversions

joblib    : 1.5.3
matplotlib: 3.10.9
numpy     : 2.4.4
pandas    : 3.0.2
re        : 2.2.1
seaborn   : 0.13.2
sklearn   : 1.8.0

---
### 03 - Carregando e Analisando os Dados

In [27]:
# definicao do nome do arquivo
nome_arquivo_csv = "dataset.csv"

In [28]:
# carregamento do dataset
df = pd.read_csv(nome_arquivo_csv)

In [29]:
# visualizando o formato
df.shape

(500, 3)

In [30]:
# visualizando as primeiras linhas
df.head()

   review_id                                       texto_review sentimento
0          1  Estou muito feliz com a compra. O cadeira game...   positivo
1          2                                                NaN   negativo
2          3  Não recomendo. A entrega foi lenta e o celular...   negativo
3          4  O monitor é decepcionante. O suporte ao client...   positivo
4          5               É UM LIVRO OK PELO PRÇEO QUE PAGUEI.   negativo

In [31]:
# amostra dos dados
df.sample(10)

     review_id                                       texto_review sentimento
429        430  A cor do fone de ouvido é um pouco diferente d...   negativo
494        495  Estou muito satisfeito com a compra. O mouse é...   positivo
13          14  RECEBI O CADEIRA GAMER HOJE. VOU COMEÇAR A USA...   negativo
113        114  Excelente notebook, superou minhas expectativa...   positivo
131        132  Recebi o mouse hoj.e Vou começar a usar para v...   positivo
90          91  Estou muito feliz com a compra. O celular é in...   positivo
84          85  Odiei o celular. Qualidade de baixa qualidade ...   positivo
254        255  Péssima experiência. O celular quebrou no prmi...   negativo
236        237  Simplesmente perfeito! O mouse funciona muito ...   positivo
465        466  Excelente cadeira gamer, superou minhas expect...   positivo

In [32]:
# visualizando as ultimas linhas
df.tail()

     review_id                                       texto_review sentimento
495        496  Odiei o teclado. Qualidade de baixa qualidade ...   negativo
496        497  Estou muito impressionado com a compra. O moni...   positivo
497        498  Não recomendo. A entrega demorou uma eternidad...   negativo
498        499  Estou muito arrependido com esta compra. Dinhe...   negativo
499        500  Ótimo custo-benefício. O cadeira gamer é incrí...   positivo

---
### 04 - Análise Exploratória de Dados (EDA)

In [33]:
# info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_id     500 non-null    int64
 1   texto_review  488 non-null    str
 2   sentimento    500 non-null    str
dtypes: int64(1), str(2)
memory usage: 48.5 KB